import Nav from "@/components/Nav";
import "./globals.css";
import { PokemonProvider } from "@/hooks/usePokemonApi";
import { BerryProvider } from "@/hooks/useBerryApi";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BerryProvider>
          <PokemonProvider>
            <Nav />
            {children}
            <Footer />
          </PokemonProvider>
        </BerryProvider>
      </body>
    </html>
  );
}
